"""Typed containers for data generated by the simulation modules.

The existing ``generate_data`` functions intentionally keep returning their
seven-element tuples.  ``GeneratedDataset`` is an adapter around that public
interface, which lets old scripts and numerical behavior remain unchanged.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Iterator, Sequence

import numpy as np


LegacyDatasetTuple = tuple[
    list[np.ndarray],
    np.ndarray,
    np.ndarray,
    Any,
    np.ndarray,
    list[np.ndarray] | None,
    np.ndarray,
]


@dataclass(frozen=True)
class GroundTruth:
    """Named ground-truth quantities returned by the current DGPs."""

    observed_adjacency: np.ndarray
    latent_adjacency: np.ndarray
    noise_scales: np.ndarray
    latent_skeleton: np.ndarray


@dataclass(frozen=True)
class GeneratedDataset:
    """A generated multi-domain dataset with an explicit truth contract.

    The arrays are stored by reference.  Adapting a legacy tuple therefore
    consumes no random numbers and does not alter values, dtypes, or shapes.
    """

    domains: list[np.ndarray]
    truth: GroundTruth
    domain_parameters: Any
    latent_samples: list[np.ndarray] | None
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_legacy_tuple(
        cls,
        values: Sequence[Any],
        *,
        metadata: dict[str, Any] | None = None,
    ) -> "GeneratedDataset":
        if len(values) != 7:
            raise ValueError(
                "A legacy DGP result must contain exactly seven values: "
                "X_list, A, B, domain_parameters, sigma, Z_list, skeleton."
            )
        domains, observed, latent, parameters, noise, z, skeleton = values
        return cls(
            domains=domains,
            truth=GroundTruth(
                observed_adjacency=observed,
                latent_adjacency=latent,
                noise_scales=noise,
                latent_skeleton=skeleton,
            ),
            domain_parameters=parameters,
            latent_samples=z,
            metadata={} if metadata is None else dict(metadata),
        )

    def to_legacy_tuple(self) -> LegacyDatasetTuple:
        """Return the original tuple layout, preserving object identities."""
        return (
            self.domains,
            self.truth.observed_adjacency,
            self.truth.latent_adjacency,
            self.domain_parameters,
            self.truth.noise_scales,
            self.latent_samples,
            self.truth.latent_skeleton,
        )

    def __iter__(self) -> Iterator[Any]:
        """Allow explicit compatibility unpacking when useful."""
        return iter(self.to_legacy_tuple())

    def observations_for_estimation(self) -> list[np.ndarray]:
        """Return only the quantities a baseline may observe."""
        return self.domains
